.TH "ary.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ary.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'dtypes.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButls\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fButls::Ary< PixelType >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Ary< unsigned char > \fButls::BAry\fP"
.br
.ti -1c
.RI "typedef Ary< int > \fButls::IAry\fP"
.br
.ti -1c
.RI "typedef Ary< unsigned int > \fButls::LAry\fP"
.br
.ti -1c
.RI "typedef Ary< float > \fButls::FAry\fP"
.br
.ti -1c
.RI "typedef Ary< double > \fButls::DAry\fP"
.br
.ti -1c
.RI "typedef Ary< void * > \fButls::PAry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
