.TH "extrema::RLEItem" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::RLEItem \- A structure that holds coordinates of a RLE element in \fBRLERegion\fP i.e. the RLE representation of a region.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libExtrema.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "int \fBcol1\fP"
.br
.ti -1c
.RI "int \fBcol2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure that holds coordinates of a RLE element in \fBRLERegion\fP i.e. the RLE representation of a region. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBextrema::RLEItem::col1\fP"
.PP
.SS "int \fBextrema::RLEItem::col2\fP"
.PP
.SS "int \fBextrema::RLEItem::line\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
