.TH "extremaParams.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extremaParams.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'extremaConfig.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBextrema\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBextrema::ExtremaImage\fP"
.br
.RI "\fIA structure holding image parameters. \fP"
.ti -1c
.RI "struct \fBextrema::ExtremaParams\fP"
.br
.RI "\fIA structure with MSER detector parameters. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGENERATE_MSER_PLUS\fP   1"
.br
.ti -1c
.RI "#define \fBGENERATE_MSER_MINUS\fP   2"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBextrema::EXTREMA_PREPROCESS\fP { \fBextrema::PREPROCESS_CHANNEL_none\fP =  0x00000000, \fBextrema::PREPROCESS_CHANNEL_intensity\fP =  0x00000001, \fBextrema::PREPROCESS_CHANNEL_saturation\fP =  0x00000002, \fBextrema::PREPROCESS_CHANNEL_hue\fP =  0x00000003, \fBextrema::PREPROCESS_CHANNEL_redblue\fP =  0x00000004, \fBextrema::PREPROCESS_CHANNEL_red\fP =  0x00000005, \fBextrema::PREPROCESS_CHANNEL_green\fP =  0x00000006, \fBextrema::PREPROCESS_CHANNEL_blue\fP =  0x00000007, \fBextrema::PREPROCESS_CHANNEL_greenmagenta\fP =  0x00000008, \fBextrema::PREPROCESS_CHANNEL_intensity_half\fP =  0x00000009, \fBextrema::PREPROCESS_CHANNEL_MASK\fP =  0x0000ffff, \fBextrema::PREPROCESS_INTENSITY_none\fP =  0x00000000, \fBextrema::PREPROCESS_INTENSITY_MASK\fP =  0xffff0000 }"
.br
.RI "\fIAn enumeration that encodes different preprocessings of an image. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define GENERATE_MSER_MINUS   2"
.PP
.SS "#define GENERATE_MSER_PLUS   1"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
