.TH "extrema::s_region" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_region \- Internal region structure.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_label\fP \fBlabel\fP"
.br
.ti -1c
.RI "int \fBminimum_int\fP"
.br
.ti -1c
.RI "int \fBpixel_total\fP"
.br
.ti -1c
.RI "int \fBborder_total\fP"
.br
.ti -1c
.RI "\fBt_ipoint\fP \fBminimum_pos\fP"
.br
.ti -1c
.RI "int \fBmaximum_int\fP"
.br
.ti -1c
.RI "\fBt_label\fP \fBmerge_label\fP"
.br
.ti -1c
.RI "t_LL \fBthresholds\fP"
.br
.ti -1c
.RI "int \fBpixels\fP [c_maxByte]"
.br
.ti -1c
.RI "int \fBborders\fP [c_maxByte]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal region structure. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBextrema::s_region::border_total\fP"
.PP
.SS "int \fBextrema::s_region::borders\fP[c_maxByte]"
.PP
.SS "\fBt_label\fP \fBextrema::s_region::label\fP"
.PP
.SS "int \fBextrema::s_region::maximum_int\fP"
.PP
.SS "\fBt_label\fP \fBextrema::s_region::merge_label\fP"
.PP
.SS "int \fBextrema::s_region::minimum_int\fP"
.PP
.SS "\fBt_ipoint\fP \fBextrema::s_region::minimum_pos\fP"
.PP
.SS "int \fBextrema::s_region::pixel_total\fP"
.PP
.SS "int \fBextrema::s_region::pixels\fP[c_maxByte]"
.PP
.SS "t_LL \fBextrema::s_region::thresholds\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
