.TH "extremaConfig.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extremaConfig.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTIME_STATS\fP   1"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TIME_STATS   1"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
