.TH "extrema::s_thresh_par" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_thresh_par \- Internal structure with processed detector's parameters.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmin_size\fP"
.br
.RI "\fIminimum size of the region in pixels \fP"
.ti -1c
.RI "int \fBmax_size\fP"
.br
.RI "\fImaximum size of the region in pixels \fP"
.ti -1c
.RI "double \fBmin_margin\fP"
.br
.RI "\fIminimum margin and upper boundary for hystheresis thresholding \fP"
.ti -1c
.RI "bool \fBrelative_margin\fP"
.br
.RI "\fImargin relative to intesity level \fP"
.ti -1c
.RI "int \fBinvert\fP"
.br
.RI "\fIdo inverted margin \fP"
.in -1c
.SH "Detailed Description"
.PP 
Internal structure with processed detector's parameters. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBextrema::s_thresh_par::invert\fP"
.PP
do inverted margin 
.PP
.SS "int \fBextrema::s_thresh_par::max_size\fP"
.PP
maximum size of the region in pixels 
.PP
.SS "double \fBextrema::s_thresh_par::min_margin\fP"
.PP
minimum margin and upper boundary for hystheresis thresholding 
.PP
.SS "int \fBextrema::s_thresh_par::min_size\fP"
.PP
minimum size of the region in pixels 
.PP
.SS "bool \fBextrema::s_thresh_par::relative_margin\fP"
.PP
margin relative to intesity level 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
