.TH "extrema::t_ipoint" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::t_ipoint \- Internal structure, holds 2D point coordinates.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal structure, holds 2D point coordinates. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBextrema::t_ipoint::x\fP"
.PP
.SS "int \fBextrema::t_ipoint::y\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
