.TH "extrema::CPreprocess" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::CPreprocess \- 
.SH SYNOPSIS
.br
.PP
\fC#include <preprocess.h>\fP
.PP
Inherited by \fBextrema::CPreprocessRGBPlanes\fP, and \fBextrema::CPreprocessRGBSeq\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBmin\fP (double a, double b) const "
.br
.ti -1c
.RI "double \fBmax\fP (double a, double b) const "
.br
.ti -1c
.RI "int \fBrgb_to_none\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_intensity\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_intensity_half\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_saturation\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_hue\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_red\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_green\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_blue\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBrgb_to_redblue\fP (const unsigned char *r, const unsigned char *g, const unsigned char *b) const "
.br
.ti -1c
.RI "int \fBinten_to_none\fP (int intensity) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int extrema::CPreprocess::inten_to_none (int intensity) const\fC [inline]\fP"
.PP
.SS "double extrema::CPreprocess::max (double a, double b) const\fC [inline]\fP"
.PP
.SS "double extrema::CPreprocess::min (double a, double b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_blue (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_green (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_hue (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_intensity (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_intensity_half (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_none (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_red (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_redblue (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP
.SS "int extrema::CPreprocess::rgb_to_saturation (const unsigned char * r, const unsigned char * g, const unsigned char * b) const\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
