.TH "extrema::s_region_equiv" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_region_equiv \- Internal structure with a node of the label equivalency tree.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBpred\fP"
.br
.ti -1c
.RI "\fBt_region\fP * \fBregion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal structure with a node of the label equivalency tree. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "unsigned int \fBextrema::s_region_equiv::pred\fP"
.PP
.SS "\fBt_region\fP* \fBextrema::s_region_equiv::region\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
