.TH "extrema::CPreprocessRGBSeq" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::CPreprocessRGBSeq \- 
.SH SYNOPSIS
.br
.PP
\fC#include <preprocess.h>\fP
.PP
Inherits \fBextrema::CPreprocess\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpreprocess\fP (const \fBExtremaImage\fP &image, int preprocess_type, \fButls::BAry\fP *&img)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void extrema::CPreprocessRGBSeq::preprocess (const \fBExtremaImage\fP & image, int preprocess_type, \fButls::BAry\fP *& img)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
