.TH "extrema::ExtremaStats" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::ExtremaStats \- Timing statistics of the detector, gathered only if TIME_STATS is set.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libExtrema.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDumpTimeStats\fP (bool both_runs=true)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum_extrema_replaced\fP"
.br
.ti -1c
.RI "double \fBinitial_time\fP"
.br
.ti -1c
.RI "double \fBpreprocess_time\fP"
.br
.ti -1c
.RI "double \fBreplace_time\fP"
.br
.ti -1c
.RI "double \fBchisto_time\fP"
.br
.ti -1c
.RI "double \fBhisto_time\fP"
.br
.ti -1c
.RI "double \fBextrema_p_time\fP"
.br
.ti -1c
.RI "double \fBoutput_p_time\fP"
.br
.ti -1c
.RI "double \fBextrema_m_time\fP"
.br
.ti -1c
.RI "double \fBoutput_m_time\fP"
.br
.ti -1c
.RI "double \fBtotal_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timing statistics of the detector, gathered only if TIME_STATS is set. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void extrema::ExtremaStats::DumpTimeStats (bool both_runs = \fCtrue\fP)"
.PP
.SH "Member Data Documentation"
.PP 
.SS "double \fBextrema::ExtremaStats::chisto_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::extrema_m_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::extrema_p_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::histo_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::initial_time\fP"
.PP
.SS "int \fBextrema::ExtremaStats::num_extrema_replaced\fP"
.PP
.SS "double \fBextrema::ExtremaStats::output_m_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::output_p_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::preprocess_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::replace_time\fP"
.PP
.SS "double \fBextrema::ExtremaStats::total_time\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
