.TH "matrix.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButls\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fButls::Matrix2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
