.TH "sortPixels.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sortPixels.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ary.h>\fP
.br
\fC#include 'extremaTypes.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBextrema\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBextrema::CalcHistogram\fP (\fButls::BAry\fP *&img, \fBt_sortpixels\fP &pixels)"
.br
.ti -1c
.RI "void \fBextrema::BinSortPixels\fP (\fButls::BAry\fP *&img, \fBt_sortpixels\fP &pixels)"
.br
.ti -1c
.RI "void \fBextrema::InvertImageAndHistogram\fP (\fButls::BAry\fP *img, \fBt_sortpixels\fP &pixels)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
