.TH "timeutls.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timeutls.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBget_time\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double get_time ()"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
