.TH "utls::t_rgb" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utls::t_rgb \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dtypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_byte\fP \fBarr\fP [3]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBt_byte\fP \fBr\fP"
.br
.ti -1c
.RI "   \fBt_byte\fP \fBg\fP"
.br
.ti -1c
.RI "   \fBt_byte\fP \fBb\fP"
.br
.ti -1c
.RI "} \fBst\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBt_byte\fP \fButls::t_rgb::arr\fP[3]"
.PP
.SS "\fBt_byte\fP \fButls::t_rgb::b\fP"
.PP
.SS "\fBt_byte\fP \fButls::t_rgb::g\fP"
.PP
.SS "\fBt_byte\fP \fButls::t_rgb::r\fP"
.PP
.SS "struct { ... }    \fButls::t_rgb::st\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
