CC = g++ -std=c++11 -pthread
#FILES = /home/pi/Documents/FYP_final/data_pi/bcode/test/test_thread.cpp
TARGET = a
O_FILES = /home/pi/Documents/FYP_final/data_pi/bcode/test/test_thread.cpp
$(TARGET):  $(O_FILES)
	$(CC) $(O_FILES) -lpthread -pthread -std=c++11
