.TH "boundary.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boundary.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ary.h>\fP
.br
\fC#include <LL.h>\fP
.br
\fC#include 'extremaTypes.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBextrema\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBextrema::RegionBoundaries\fP (\fButls::BAry\fP *img, t_LL regions)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
