.TH "extrema::ExtremaParams" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::ExtremaParams \- A structure with MSER detector parameters.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaParams.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtremaParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBrelative\fP"
.br
.ti -1c
.RI "int \fBpreprocess\fP"
.br
.ti -1c
.RI "int \fBmin_size\fP"
.br
.ti -1c
.RI "double \fBmax_area\fP"
.br
.ti -1c
.RI "double \fBmin_margin\fP"
.br
.ti -1c
.RI "bool \fBverbose\fP"
.br
.ti -1c
.RI "int \fBdebug\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure with MSER detector parameters. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "extrema::ExtremaParams::ExtremaParams ()\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBextrema::ExtremaParams::debug\fP"
.PP
.SS "double \fBextrema::ExtremaParams::max_area\fP"
.PP
.SS "double \fBextrema::ExtremaParams::min_margin\fP"
.PP
.SS "int \fBextrema::ExtremaParams::min_size\fP"
.PP
.SS "int \fBextrema::ExtremaParams::preprocess\fP"
.PP
.SS "bool \fBextrema::ExtremaParams::relative\fP"
.PP
.SS "bool \fBextrema::ExtremaParams::verbose\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
