.TH "extrema::s_thresh_def" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_thresh_def \- Internal structure holding threshold paramaters.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBthresh\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "int \fBmargin\fP"
.br
.ti -1c
.RI "\fBpoint_vector\fP * \fBboundary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal structure holding threshold paramaters. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBpoint_vector\fP* \fBextrema::s_thresh_def::boundary\fP"
.PP
.SS "int \fBextrema::s_thresh_def::margin\fP"
.PP
.SS "int \fBextrema::s_thresh_def::pos\fP"
.PP
.SS "int \fBextrema::s_thresh_def::thresh\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
