.TH "extrema::BoundaryRegion" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::BoundaryRegion \- Description of a boundary region.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libExtrema.h>\fP
.PP
Inherits \fBextrema::Region\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBBoundaryRegion\fP &a) const "
.br
.RI "\fIStability ordering operator. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBBoundaryPoint\fP > \fBboundary\fP"
.br
.RI "\fIVector that holds boundary representation of the region. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Description of a boundary region. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool extrema::BoundaryRegion::operator< (const \fBBoundaryRegion\fP & a) const\fC [inline]\fP"
.PP
Stability ordering operator. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBBoundaryPoint\fP> \fBextrema::BoundaryRegion::boundary\fP"
.PP
Vector that holds boundary representation of the region. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
