.TH "extrema::s_suballocator" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_suballocator \- Internal structure with suballocator's data.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <suballoc.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "t_LL \fBitems\fP"
.br
.ti -1c
.RI "t_LL \fBblocks\fP"
.br
.ti -1c
.RI "size_t \fBfree_items\fP"
.br
.ti -1c
.RI "size_t \fBitem_size\fP"
.br
.ti -1c
.RI "size_t \fBblock_size\fP"
.br
.ti -1c
.RI "int \fBclear_blocks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal structure with suballocator's data. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "size_t \fBextrema::s_suballocator::block_size\fP"
.PP
.SS "t_LL \fBextrema::s_suballocator::blocks\fP"
.PP
.SS "int \fBextrema::s_suballocator::clear_blocks\fP"
.PP
.SS "size_t \fBextrema::s_suballocator::free_items\fP"
.PP
.SS "size_t \fBextrema::s_suballocator::item_size\fP"
.PP
.SS "t_LL \fBextrema::s_suballocator::items\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
