.TH "extrema::s_borderpixel" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_borderpixel \- Structure with pixel of the extended boundary.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBs_borderpixel\fP &other) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_ipoint\fP \fBpos\fP"
.br
.ti -1c
.RI "unsigned char \fBdirect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure with pixel of the extended boundary. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "bool extrema::s_borderpixel::operator< (const \fBs_borderpixel\fP & other) const\fC [inline]\fP"
.PP
.SH "Member Data Documentation"
.PP 
.SS "unsigned char \fBextrema::s_borderpixel::direct\fP"
.PP
.SS "\fBt_ipoint\fP \fBextrema::s_borderpixel::pos\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
