.TH "extrema::RLEExtrema" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::RLEExtrema \- Old interface structure that holds result of getRLEExtrema.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libExtrema.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBRLERegion\fP > \fBMSERplus\fP"
.br
.ti -1c
.RI "vector< \fBRLERegion\fP > \fBMSERmin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Old interface structure that holds result of getRLEExtrema. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBRLERegion\fP> \fBextrema::RLEExtrema::MSERmin\fP"
.PP
.SS "vector<\fBRLERegion\fP> \fBextrema::RLEExtrema::MSERplus\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
