.TH "extrema::s_sortpixels" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::s_sortpixels \- Internal structure with intensity histogram.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaTypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBt_ipoint\fP * \fBdata\fP [c_maxByte]"
.br
.ti -1c
.RI "int \fBhist\fP [c_maxByte]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal structure with intensity histogram. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "\fBt_ipoint\fP* \fBextrema::s_sortpixels::data\fP[c_maxByte]"
.PP
.SS "int \fBextrema::s_sortpixels::hist\fP[c_maxByte]"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
