.TH "extrema::ExtremaImage" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::ExtremaImage \- A structure holding image parameters.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <extremaParams.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.RI "\fIWidth of the image. \fP"
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.RI "\fIHeight of the image. \fP"
.ti -1c
.RI "unsigned int \fBchannels\fP"
.br
.RI "\fINumber of channels of the image. \fP"
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.RI "\fIPointer to image data. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A structure holding image parameters. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "unsigned int \fBextrema::ExtremaImage::channels\fP"
.PP
Number of channels of the image. 
.PP
.SS "unsigned char* \fBextrema::ExtremaImage::data\fP"
.PP
Pointer to image data. 
.PP
.SS "unsigned int \fBextrema::ExtremaImage::height\fP"
.PP
Height of the image. 
.PP
.SS "unsigned int \fBextrema::ExtremaImage::width\fP"
.PP
Width of the image. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
