.TH "extrema::BoundaryExtrema" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extrema::BoundaryExtrema \- Old interface structure that holds result of getBoundaryExtrema.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <libExtrema.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBBoundaryRegion\fP > \fBMSERplus\fP"
.br
.ti -1c
.RI "vector< \fBBoundaryRegion\fP > \fBMSERmin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Old interface structure that holds result of getBoundaryExtrema. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBBoundaryRegion\fP> \fBextrema::BoundaryExtrema::MSERmin\fP"
.PP
.SS "vector<\fBBoundaryRegion\fP> \fBextrema::BoundaryExtrema::MSERplus\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
