.TH "getExtrema.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getExtrema.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LL.h>\fP
.br
\fC#include <ary.h>\fP
.br
\fC#include 'extremaParams.h'\fP
.br
\fC#include 'extremaTypes.h'\fP
.br
\fC#include 'suballoc.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBextrema\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBextrema::InitRegionRecycling\fP ()"
.br
.ti -1c
.RI "void \fBextrema::DestRegionRecycling\fP ()"
.br
.ti -1c
.RI "t_LL \fBextrema::GetExtrema\fP (\fButls::BAry\fP *img, \fBt_sortpixels\fP pixels, const ExtremaParams &par, bool invert)"
.br
.ti -1c
.RI "void \fBextrema::DestRegions\fP (t_LL regions)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBt_thresh_par\fP \fBextrema::g_thresh_params\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
