.TH "suballoc.h" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
suballoc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LL.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBextrema\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBextrema::s_suballocator\fP"
.br
.RI "\fIInternal structure with suballocator's data. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBextrema::s_suballocator\fP \fBextrema::t_suballocator\fP"
.br
.RI "\fIInternal structure with suballocator's data. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBextrema::InitSuballocator\fP (\fBt_suballocator\fP *s, size_t blocksize, size_t itemsize, int clear_blocks=0)"
.br
.ti -1c
.RI "void \fBextrema::DestSuballocator\fP (\fBt_suballocator\fP *s)"
.br
.ti -1c
.RI "void \fBextrema::SuballocatorAddBlock\fP (\fBt_suballocator\fP *s)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
