.TH "utls::t_frgb" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utls::t_frgb \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dtypes.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBarr\fP [3]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   float \fBr\fP"
.br
.ti -1c
.RI "   float \fBg\fP"
.br
.ti -1c
.RI "   float \fBb\fP"
.br
.ti -1c
.RI "} \fBst\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float \fButls::t_frgb::arr\fP[3]"
.PP
.SS "float \fButls::t_frgb::b\fP"
.PP
.SS "float \fButls::t_frgb::g\fP"
.PP
.SS "float \fButls::t_frgb::r\fP"
.PP
.SS "struct { ... }     \fButls::t_frgb::st\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
