.TH "utls" 3 "22 Oct 2006" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utls \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAry\fP"
.br
.ti -1c
.RI "union \fBt_rgb\fP"
.br
.ti -1c
.RI "union \fBt_frgb\fP"
.br
.ti -1c
.RI "class \fBMatrix2\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAry\fP< unsigned char > \fBBAry\fP"
.br
.ti -1c
.RI "typedef \fBAry\fP< int > \fBIAry\fP"
.br
.ti -1c
.RI "typedef \fBAry\fP< unsigned int > \fBLAry\fP"
.br
.ti -1c
.RI "typedef \fBAry\fP< float > \fBFAry\fP"
.br
.ti -1c
.RI "typedef \fBAry\fP< double > \fBDAry\fP"
.br
.ti -1c
.RI "typedef \fBAry\fP< void * > \fBPAry\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBt_byte\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAry\fP<unsigned char> \fButls::BAry\fP"
.PP
.SS "typedef \fBAry\fP<int> \fButls::IAry\fP"
.PP
.SS "typedef \fBAry\fP<unsigned int> \fButls::LAry\fP"
.PP
.SS "typedef \fBAry\fP<float> \fButls::FAry\fP"
.PP
.SS "typedef \fBAry\fP<double> \fButls::DAry\fP"
.PP
.SS "typedef \fBAry\fP<void *> \fButls::PAry\fP"
.PP
.SS "typedef unsigned char \fButls::t_byte\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
